# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '9ed5d963b51a0a61b17377775f52b836'
  config.secret_key = 'd6101f0176ca3eb8780eafc27540a5d0'
  config.default_from = 'hello@woonies.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
